In [1]:
!pip3 install numpy

# Numpy Tutorial 

In [2]:
import numpy as np  ## prviding shortname for numpy
arr=np.array([[1,2,3],[4,5,6]])
type(arr)


numpy.ndarray

In [3]:
print("No of dimensions", arr.ndim)

No of dimensions 2


In [4]:
print("Shape of array",arr.shape)## telling no of rows and column

Shape of array (2, 3)


In [5]:
b=np.array([1,2,3])
print(b.shape)## anything like (4,) or (3,) etc are 1d array

(3,)


In [6]:
# creating array from list with type float
a=np.array([[1,2,3],[5,6,7]], dtype="float")
print(a)

[[1. 2. 3.]
 [5. 6. 7.]]


In [7]:
b=np.array((1,2,3))
print(b)

[1 2 3]


In [8]:
c=np.zeros((3,4))## creating a matrix and initializing everything with zeros
print(c)## By default thier datatype is float

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
d=np.ones((3,4), dtype="int")
print(d)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [12]:
e=np.eye(3)## diagonal will be 1 and creating 3X3 Matrix
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
np.arange?## using '?' to read about

In [15]:
f=np.arange(3)
print(f)

[0 1 2]


In [22]:
g=np.arange(0,30,5)## starting from 0 and ending till n-1 with steps of 5
print(g)

[ 0  5 10 15 20 25]


In [26]:
h=np.linspace(0,5,10)## create a sequence of 10 values in range 0,5
print(h)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [27]:
i=np.random.random((2,2))## creating a matrix of 2X2 of random values
print(i)

[[0.99454367 0.80615681]
 [0.82176688 0.15752559]]


In [30]:
arr=np.array([[1,2,3,4],
              [5,2,4,2],
              [1,2,0,1]])
newarr=arr.reshape((4,3))  ##reshapping the matrix
print(newarr)

[[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [31]:
arr

array([[1, 2, 3, 4],
       [5, 2, 4, 2],
       [1, 2, 0, 1]])

In [32]:
arr[1:,:3]## before coma represent row starting from 2nd row and after comma it represent column till 3rd column

array([[5, 2, 4],
       [1, 2, 0]])

In [35]:
arr[1:,:3:2]## skip 2nd column

array([[5, 4],
       [1, 0]])

In [36]:
## arr[start:end-1:step, start:end-1:tep]

In [43]:
temp = np.array([[0, 1, 2, 4], [7, 6, 4, 2], [3, 5, 1, 0]])
cond = temp > 2
result = temp[cond]
print(result)

[4 7 6 4 3 5]


In [44]:
a=np.array([1,2,4,5])## adding 1 in every single element
a+1

array([2, 3, 5, 6])

In [45]:
a*3 ##multiplying

array([ 3,  6, 12, 15])

In [46]:
a**2

array([ 1,  4, 16, 25], dtype=int32)

In [48]:
a+=2
print(a)

[5 6 8 9]


In [54]:
a=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(a)
print()
print("After transpose")
print(a.T)## transpose of array

[[1 2 3]
 [4 5 6]
 [7 8 9]]

After transpose
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [55]:
a.max()## result of maximum element in an array

9

In [56]:
a.max(axis=1)## axis=1 means you going to print output rowise

array([3, 6, 9])

In [57]:
a.max(axis=0) ##printing column wise

array([7, 8, 9])

In [58]:
arr.sum()

27

In [59]:
arr.cumsum(axis=1)

array([[ 1,  3,  6, 10],
       [ 5,  7, 11, 13],
       [ 1,  3,  3,  4]], dtype=int32)

In [61]:
b=np.array(([5,6],[7,8]))
a=np.array(([1,2],[3,4]))

In [62]:
a+b ## adding matrix

array([[ 6,  8],
       [10, 12]])

In [63]:
a.dot(b)## matrix multiplication

array([[19, 22],
       [43, 50]])

In [66]:
temp = np.array([[0, 1, 2, 4], [7, 6, 4, 2], [3, 5, 1, 0]])
print(np.sort(temp,axis=None))

[0 0 1 1 2 2 3 4 4 5 6 7]


In [67]:
print(np.sort(temp,axis=1))#going to sort every row

[[0 1 2 4]
 [2 4 6 7]
 [0 1 3 5]]


In [68]:
print(np.sort(temp,axis=0))

[[0 1 1 0]
 [3 5 2 2]
 [7 6 4 4]]


In [69]:
print(np.sort(temp,axis=None,kind="mergesort")) #specify sorting algorithm

[0 0 1 1 2 2 3 4 4 5 6 7]


In [71]:
print(np.vstack((a,b)))##stacking in vertical way

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [72]:
print(np.hstack((a,b))) stacking in horizontal way

[[1 2 5 6]
 [3 4 7 8]]
